server.port=8080

# Conexión local a PostgreSQL usando variables de entorno
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskmanager_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Propiedades JWT protegidas
jwt.secret=${JWT_SECRET}
jwt.access.expiration=900000
jwt.refresh.expiration=604800000
cors.allowed-origins=http://localhost:4200
